//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserGRBLCore {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LaserGRBLCore.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BoxAutoUpdateFailed {
            get {
                return ResourceManager.GetString("BoxAutoUpdateFailed", resourceCulture);
            }
        }
        
        internal static string BoxAutoUpdateRequireAdmin {
            get {
                return ResourceManager.GetString("BoxAutoUpdateRequireAdmin", resourceCulture);
            }
        }
        
        internal static string BoxAutoUpdateResult {
            get {
                return ResourceManager.GetString("BoxAutoUpdateResult", resourceCulture);
            }
        }
        
        internal static string BoxAutoUpdateSuccess {
            get {
                return ResourceManager.GetString("BoxAutoUpdateSuccess", resourceCulture);
            }
        }
        
        internal static string BoxConfigDetectedChanges {
            get {
                return ResourceManager.GetString("BoxConfigDetectedChanges", resourceCulture);
            }
        }
        
        internal static string BoxConfigDetectedChangesTitle {
            get {
                return ResourceManager.GetString("BoxConfigDetectedChangesTitle", resourceCulture);
            }
        }
        
        internal static string BoxConnectErrorTitle {
            get {
                return ResourceManager.GetString("BoxConnectErrorTitle", resourceCulture);
            }
        }
        
        internal static string BoxExportConfigError {
            get {
                return ResourceManager.GetString("BoxExportConfigError", resourceCulture);
            }
        }
        
        internal static string BoxExportConfigErrorTitle {
            get {
                return ResourceManager.GetString("BoxExportConfigErrorTitle", resourceCulture);
            }
        }
        
        internal static string BoxExportConfigFileNotFound {
            get {
                return ResourceManager.GetString("BoxExportConfigFileNotFound", resourceCulture);
            }
        }
        
        internal static string BoxExportConfigSuccess {
            get {
                return ResourceManager.GetString("BoxExportConfigSuccess", resourceCulture);
            }
        }
        
        internal static string BoxExportConfigSuccessTitle {
            get {
                return ResourceManager.GetString("BoxExportConfigSuccessTitle", resourceCulture);
            }
        }
        
        internal static string BoxImportConfigFileError {
            get {
                return ResourceManager.GetString("BoxImportConfigFileError", resourceCulture);
            }
        }
        
        internal static string BoxImportConfigWithError {
            get {
                return ResourceManager.GetString("BoxImportConfigWithError", resourceCulture);
            }
        }
        
        internal static string BoxImportConfigWithoutError {
            get {
                return ResourceManager.GetString("BoxImportConfigWithoutError", resourceCulture);
            }
        }
        
        internal static string BoxReadConfigError {
            get {
                return ResourceManager.GetString("BoxReadConfigError", resourceCulture);
            }
        }
        
        internal static string BoxReadConfigPleaseConnect {
            get {
                return ResourceManager.GetString("BoxReadConfigPleaseConnect", resourceCulture);
            }
        }
        
        internal static string BoxReadConfigSuccess {
            get {
                return ResourceManager.GetString("BoxReadConfigSuccess", resourceCulture);
            }
        }
        
        internal static string BoxWriteConfigNoChange {
            get {
                return ResourceManager.GetString("BoxWriteConfigNoChange", resourceCulture);
            }
        }
        
        internal static string BoxWriteConfigWithError {
            get {
                return ResourceManager.GetString("BoxWriteConfigWithError", resourceCulture);
            }
        }
        
        internal static string BoxWriteConfigWithoutError {
            get {
                return ResourceManager.GetString("BoxWriteConfigWithoutError", resourceCulture);
            }
        }
        
        internal static string CustomButtonEdit {
            get {
                return ResourceManager.GetString("CustomButtonEdit", resourceCulture);
            }
        }
        
        internal static string CustomButtonRemove {
            get {
                return ResourceManager.GetString("CustomButtonRemove", resourceCulture);
            }
        }
        
        internal static string DirectionDiagonal {
            get {
                return ResourceManager.GetString("DirectionDiagonal", resourceCulture);
            }
        }
        
        internal static string DirectionHorizontal {
            get {
                return ResourceManager.GetString("DirectionHorizontal", resourceCulture);
            }
        }
        
        internal static string DirectionNone {
            get {
                return ResourceManager.GetString("DirectionNone", resourceCulture);
            }
        }
        
        internal static string DirectionVertical {
            get {
                return ResourceManager.GetString("DirectionVertical", resourceCulture);
            }
        }
        
        internal static string DisconnectAnyway {
            get {
                return ResourceManager.GetString("DisconnectAnyway", resourceCulture);
            }
        }
        
        internal static string ExitAnyway {
            get {
                return ResourceManager.GetString("ExitAnyway", resourceCulture);
            }
        }
        
        internal static string FormulaCustom {
            get {
                return ResourceManager.GetString("FormulaCustom", resourceCulture);
            }
        }
        
        internal static string FormulaOpticalCorrect {
            get {
                return ResourceManager.GetString("FormulaOpticalCorrect", resourceCulture);
            }
        }
        
        internal static string FormulaSimpleAverage {
            get {
                return ResourceManager.GetString("FormulaSimpleAverage", resourceCulture);
            }
        }
        
        internal static string FormulaWeightAverage {
            get {
                return ResourceManager.GetString("FormulaWeightAverage", resourceCulture);
            }
        }
        
        internal static string InterpolationModeHighQualityBicubic {
            get {
                return ResourceManager.GetString("InterpolationModeHighQualityBicubic", resourceCulture);
            }
        }
        
        internal static string InterpolationModeNearestNeighbor {
            get {
                return ResourceManager.GetString("InterpolationModeNearestNeighbor", resourceCulture);
            }
        }
        
        internal static string LanguageRequireRestart {
            get {
                return ResourceManager.GetString("LanguageRequireRestart", resourceCulture);
            }
        }
        
        internal static string LanguageRequireRestartNow {
            get {
                return ResourceManager.GetString("LanguageRequireRestartNow", resourceCulture);
            }
        }
        
        internal static string MacStatusAlarm {
            get {
                return ResourceManager.GetString("MacStatusAlarm", resourceCulture);
            }
        }
        
        internal static string MacStatusCheck {
            get {
                return ResourceManager.GetString("MacStatusCheck", resourceCulture);
            }
        }
        
        internal static string MacStatusConnecting {
            get {
                return ResourceManager.GetString("MacStatusConnecting", resourceCulture);
            }
        }
        
        internal static string MacStatusDisconnected {
            get {
                return ResourceManager.GetString("MacStatusDisconnected", resourceCulture);
            }
        }
        
        internal static string MacStatusDoor {
            get {
                return ResourceManager.GetString("MacStatusDoor", resourceCulture);
            }
        }
        
        internal static string MacStatusHold {
            get {
                return ResourceManager.GetString("MacStatusHold", resourceCulture);
            }
        }
        
        internal static string MacStatusHome {
            get {
                return ResourceManager.GetString("MacStatusHome", resourceCulture);
            }
        }
        
        internal static string MacStatusIdle {
            get {
                return ResourceManager.GetString("MacStatusIdle", resourceCulture);
            }
        }
        
        internal static string MacStatusJog {
            get {
                return ResourceManager.GetString("MacStatusJog", resourceCulture);
            }
        }
        
        internal static string MacStatusRun {
            get {
                return ResourceManager.GetString("MacStatusRun", resourceCulture);
            }
        }
        
        internal static string MacStatusUnknown {
            get {
                return ResourceManager.GetString("MacStatusUnknown", resourceCulture);
            }
        }
        
        internal static string MainFormEstimatedTime {
            get {
                return ResourceManager.GetString("MainFormEstimatedTime", resourceCulture);
            }
        }
        
        internal static string MainFormProjectedTime {
            get {
                return ResourceManager.GetString("MainFormProjectedTime", resourceCulture);
            }
        }
        
        internal static string ResumeJobHomingRequired {
            get {
                return ResourceManager.GetString("ResumeJobHomingRequired", resourceCulture);
            }
        }
        
        internal static string ResumeJobHomingRequiredTitle {
            get {
                return ResourceManager.GetString("ResumeJobHomingRequiredTitle", resourceCulture);
            }
        }
    }
}
